export const siteContent = {
  brand: {
    name: "DeepPrior",
    tagline: "Quantitative Research in Energy Markets and Power Systems",
    heroIntro:
      "We are a quantitative research organization developing advanced AI forecasting models for energy markets and power systems.",
    heroHeadline: "Quantitative Research Organization",
    footerNote: "A Quantitative Energy Research Organization",
  },
  sectionVideos: {
    committee: "Video/aaaa.mp4",
    research: "",
    analysis: "",
    about: "",
  },
  committee: {
    eyebrow: "Committee",
    title: "DeepPrior",
    description:
      "At DeepPrior, we are an international and diverse team of researchers from prestigious institutes.",
    members: [
      {
        name: "Runyao Yu",
        role: "Founder",
        initials: "RY",
        universities: ["Delft University of Technology"],
        links: {
          website: "https://runyao-yu.com/",
          linkedin: "https://www.linkedin.com/in/runyao-yu/",
          github: "https://github.com/runyao-yu",
          email: "runyao.yu@tudelft.nl",
        },
        bio: "Runyao advances uncertainty-aware electricity price forecasting across day-ahead, intraday, and balancing markets, with a focus on probabilistic modeling, market microstructure, and foundation models for energy systems. His academic path includes a PhD at TU Delft and an MSc from TU Munich, complemented by visiting positions at ETH Zurich and London Business School. Alongside academia, he serves as Lead Data Scientist at (Bugatti-) Rimac Automobili, with industrial experience at BMW, Danfoss, KPMG, and Arup. At DeepPrior, Runyao leads research at the intersection of AI, forecasting, and real-world energy market decision-making.",
        image: "Figure/Committee/runyao.png",
      },
      {
        name: "Ruiling Ding",
        role: "Co-Founder",
        initials: "RD",
        universities: ["Frankfurt School of Finance & Management"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/ruiling-ding-49b743161/",
          github: "",
          email: "ruilingding07@gmail.com",
        },
        bio: "Ruiling combines top-tier financial rigor with strategic development for high-growth technology. Her foundation is anchored in Investment Banking at Morgan Stanley and SMBC in London and Frankfurt, with professional tenures at PwC, Infineon, and Deutsche Börse. With a background in international business development for Chinese SaaS and robotics startups, she bridges the gap between technical research and commercial strategy. Ruiling holds an MSc in Finance from Frankfurt School, with international studies at UC Berkeley and UBC. At DeepPrior, she steers operations and finance within the European energy forecasting sector.",
        image: "Figure/Committee/ruiling.png",
      },
        {
        name: "Prof. Derek W. Bunn",
        role: "Chair",
        initials: "DWB",
        universities: ["London Business School"],
        links: {
          website: "https://www.london.edu/faculty-and-research/faculty-profiles/b/bunn-dw",
          linkedin: "",
          github: "",
          email: "dbunn@london.edu",
        },
        bio: "Derek works at the intersection of forecasting, decision analysis, and energy economics through a career spanning academic leadership, editorial stewardship, and policy advisory work. He is Professor of Decision Sciences at London Business School, where his research has shaped management science and energy market analysis through more than 250 publications and 9 books. His academic path includes an MA from Cambridge, MSc and PhD degrees from London, and a CEGB Engineering Fellowship at Oxford. Alongside academia, Derek has served in leading roles across the field, including chief editorships at the Journal of Forecasting and Energy Economics, founding editorship of the Journal of Energy Markets, and advisory appointments to UK government and electricity market institutions. At the intersection of forecasting, energy, and decision-making, his work continues to influence both scholarship and real-world market design.",
        image: "Figure/Committee/derek.png",
      },

            {
        name: "Prof. Qingsong Wen",
        role: "Chair",
        initials: "QW",
        universities: ["University of Oxford"],
        links: {
          website: "https://sites.google.com/site/qingsongwen8/",
          linkedin: "https://www.linkedin.com/in/qingsong-wen-22814156/",
          github: "",
          email: "qingsongedu@gmail.com",
        },
        bio: "Qingsong Wen is PhD Supervisor at the University of Oxford, a Forbes Top 100 Most Influential Chinese Elite, and Head of AI & Chief Scientist at Squirrel Ai Learning. He specializes in machine learning, data mining, and signal processing, with a particular focus on AI for time series. His academic path includes an M.S. and Ph.D. in Electrical and Computer Engineering from Georgia Tech, complemented by industrial experience at Alibaba, Qualcomm, and Marvell. He has published over 200 papers with more than 20,000 citations, and holds leadership roles across IEEE and INNS, including Chair of the IEEE CIS Task Force on AI for Time Series and Spatio-Temporal Data. At DeepPrior, Qingsong advises research at the intersection of AI, time-series modeling, and intelligent decision-making systems.",
        image: "Figure/Committee/qingsong.png",
      },
      {
        name: "Prof. Peter Palensky",
        role: "Chair",
        initials: "PP",
        universities: ["Delft University of Technology"],
        links: {
          website: "https://palensky.org/",
          linkedin: "https://www.linkedin.com/in/peter-palensky/",
          github: "",
          email: "p.palensky@tudelft.nl",
        },
        bio: "Peter specializes in intelligent power systems research across grid digitalization, integrated energy systems, and cyber-physical energy infrastructure, with a focus on modeling and simulation, digital twins, automation, and secure operation of future power grids. His academic path includes a full Professorship at TU Delft and doctoral training at Vienna University of Technology, complemented by leadership and research roles at Lawrence Berkeley National Laboratory, the University of Pretoria, and the Austrian Institute of Technology. Alongside academia, he has built and led research with strong industrial relevance, spanning energy automation, smart cities, and sustainable buildings. At DeepPrior, Peter brings senior leadership in intelligent power grids, digital twins, and large-scale energy system innovation.",
        image: "Figure/Committee/peter.png",
      },

      {
        name: "Prof. Haiyan Lu",
        role: "Chair",
        initials: "HL",
        universities: ["University of Technology Sydney"],
        links: {
          website: "https://profiles.uts.edu.au/Haiyan.Lu",
          linkedin: "",
          github: "",
          email: "Haiyan.Lu@uts.edu.au",
        },
        bio: "Haiyan works on artificial intelligence, data analytics, and time series modelling, with a focus on decision systems, intelligent services, and trustworthy digital systems. She serves as Head of Discipline in Data Analytics. At DeepPrior, Haiyan brings leadership in AI, data science, and intelligent decision-making for real-world digital and energy applications.",
        image: "Figure/Committee/haiyan.png",
      },
      {
        name: "Prof. Jochen L. Cremer",
        role: "Chair",
        initials: "JLC",
        universities: ["Delft University of Technology"],
        links: {
          website: "https://www.jochen-cremer.com/",
          linkedin: "https://www.linkedin.com/in/jochen-cremer/",
          github: "",
          email: "J.L.Cremer@tudelft.nl",
        },
        bio: "Jochen advances AI-driven power system operation across reliability, security, and resilience, with a focus on machine learning, physics-informed methods, and data-driven control for complex energy systems. His academic path includes an Associate Professorship at TU Delft and a PhD from Imperial College London, complemented by earlier research experience at Carnegie Mellon University and MIT, as well as multidisciplinary training at RWTH Aachen University. Alongside academia, he serves as Principal Scientist at the Austrian Institute of Technology and co-director of Student Energy. At DeepPrior, Jochen serves as Committee Chair, supporting research at the intersection of AI and energy systems.",
        image: "Figure/Committee/jochenc.png",
      },
      {
        name: "Tara Esterl",
        role: "Chair",
        initials: "TE",
        universities: ["Austrian Institute of Technology"],
        links: {
          website: "https://www.ait.ac.at/en/research-topics/flexibility-business-models",
          linkedin: "https://www.linkedin.com/in/tara-esterl-68026a1b/",
          github: "",
          email: "Tara.Esterl@ait.ac.at",
        },
        bio: "Tara works on energy market flexibility and integrated energy systems, with a focus on regulatory frameworks, storage economics, local flexibility markets, and the integration of energy communities. She is Head of Integrated Energy Systems at the Austrian Institute of Technology, where she leads research on market and grid integration, large-scale storage, and resilient energy system design. At DeepPrior, Tara brings leadership in flexibility markets, storage business models, and sustainable power system innovation.",
        image: "Figure/Committee/tara.png",
      },
      {
        name: "Dr. Shen Li",
        role: "Member",
        initials: "SL",
        universities: ["Imperial College London"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/shen-li-42012983/",
          github: "",
          email: "Shen.Li@fortescue.com",
        },
        image: "Figure/Committee/shen.png",
        bio: "Shen specializes in battery systems and intelligent vehicles. His academic path includes a PhD from Tsinghua University and postdoctoral research at Imperial College London, complemented by strong publication records in  intelligent transportation and battery modeling. Alongside academia, he has brought this expertise into industry through his role as Senior Battery Engineer at (Bugatti-) Rimac. At DeepPrior, he brings cross-domain strength in battery intelligence and data-driven mobility research.",
      },
      {
        name: "Dr. Zihao Zhou",
        role: "Member",
        initials: "ZZ",
        universities: ["University of Oxford"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/zihao-zhou-5b281b12b/",
          github: "",
          email: "zihaobattery@gmail.com",
        },
        bio: "Zihao focuses on AI for battery aging, with a focus on reliability modeling, early-life SOH prediction, and hybrid electrochemical-AI methods for lithium-ion batteries. His academic path includes a PhD in Electrical and Electronics Engineering from the University of Oxford and an MSc in the same field from Tsinghua University, providing a strong foundation in battery systems and intelligent modeling. Alongside academia, he serves as Senior Reliability Modeling and Optimization Engineer at CATL, with industrial experience spanning Huawei and Tencent. At DeepPrior, Zihao contributes to research at the intersection of AI, battery aging, and next-generation energy technologies.",
        image: "Figure/Committee/zihao.png",
      },
      {
        name: "Dr. Jochen Stiasny",
        role: "Member",
        initials: "JS",
        universities: ["Delft University of Technology"],
        links: {
          website: "https://www.tudelft.nl/en/staff/j.b.stiasny/",
          linkedin: "https://www.linkedin.com/in/jochen-stiasny-83184a1b1/",
          github: "https://github.com/jbesty",
          email: "j.b.stiasny@tudelft.nl",
        },
        bio: "Jochen contributes to AI for power systems, with a focus on scientific machine learning, physics-informed neural networks, and data-driven methods for energy system modeling and control. His academic path includes a PhD in Wind and Energy Systems from DTU, complemented by postdoctoral research at TU Delft, an external research stay at the University of Washington, and earlier engineering training across ETH Zurich, Lund University, and Technische Universität Darmstadt. Alongside academia, he brings hands-on engineering experience from AMZ Racing and Adaptricity. At DeepPrior, Jochen contributes to research at the intersection of AI, power systems, and next-generation energy infrastructure.",
        image: "Figure/Committee/jochens.png",
      },

      {
        name: "Dr. Andreas Billert",
        role: "Member",
        initials: "AB",
        universities: ["Karlsruhe Institute of Technology"],
        links: {
          website: "https://www.fast.kit.edu/lff/Automatisierung_13527.php",
          linkedin: "https://www.linkedin.com/in/dr-ing-andreas-billert-2a0a11226/",
          github: "",
          email: "andreas.billert@partner.kit.edu",
        },
        bio: "Andreas specializes in AI for battery systems, with a focus on machine learning, charging, and software function development for high-voltage batteries. His academic path includes doctoral research in batteries and machine learning in cooperation between BMW and KIT, complemented by an MSc in Automotive Technology and a BSc in Engineering Science from the Technical University of Munich, as well as study-abroad experience at Shanghai Jiao Tong University and UC Berkeley. Alongside academia, he serves as Cluster Leader at BMW, where he leads charging and digitalization for battery software function development, with earlier experience spanning battery modeling, automotive research, and engineering practice. At DeepPrior, Andreas contributes to research at the intersection of AI, battery intelligence, and next-generation mobility systems.",
        image: "Figure/Committee/andreas.png",
      },
      {
        name: "Yuchen Tao",
        role: "Member",
        initials: "YT",
        universities: ["RWTH Aachen"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/yuchen-tao/",
          github: "",
          email: "yuchen.tao@rwth-aachen.de",
        },
        bio: "Yuchen advances AI for automated driving, with a focus on perception, intelligent systems, and real-world deployment of advanced driving technologies. His academic path includes studies at RWTH Aachen University and Shanghai Jiao Tong University, providing a strong foundation across engineering and applied AI. Alongside academia, he serves as Senior AI Engineer, with industrial experience spanning Hyundai, Bosch, and Volkswagen. At DeepPrior, Yuchen contributes to advanced software development for energy trading.",
        image: "Figure/Committee/yuchen.png",
      },
      {
        name: "Yuqicheng Zhu",
        role: "Member",
        initials: "YZ",
        universities: ["Max Planck Institute"],
        links: {
          website: "https://zhuyuqicheng.github.io/",
          linkedin: "https://www.linkedin.com/in/yuqicheng-zhu-531658161/",
          github: "https://github.com/ZhuYuqicheng",
          email: "",
        },
        bio: "Yuqicheng specializes in large language models, AI agents, and knowledge graphs. He received his PhD from the Max Planck Institute and the University of Stuttgart, and his MSc from TU Munich, with a visiting position at Oxford University. He also brings industrial experience from Bosch (BCAI).",
        image: "Figure/Committee/yuqicheng.png",
      },
      {
        name: "Lianlian Qi",
        role: "Member",
        initials: "LQ",
        universities: ["Technical University of Munich"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/lianlian-qi-a3257a147/",
          github: "",
          email: "lianlian.qi@ait.ac.at",
        },
        bio: "Lianlian shapes AI for intelligent urban design, with a focus on deep learning, human-centered systems, and data-driven approaches for shaping more adaptive urban environments. Her academic path includes doctoral research at the Technical University of Munich and Austrian Institute of Technology, complemented by an MSc in Artificial Intelligence from the University of Edinburgh. Alongside academia, her industrial experience spans leading technology companies including ByteDance and DiDi. At DeepPrior, Lianlian contributes to research at the intersection of AI, design, and real-world urban innovation.",
        image: "Figure/Committee/lianlian.png",
      },
      {
        name: "Yujie Chen",
        role: "Member",
        initials: "YC",
        universities: ["The Chinese University of Hong Kong"],
        links: {
          website: "https://yujiechen8888.github.io/",
          linkedin: "",
          github: "https://github.com/YujieChen8888",
          email: "chenyujie@cuhk.edu.cn",
        },
        bio: "Yujie works on load forecasting, deep learning, and artificial intelligence for energy systems. He is a PhD researcher at The Chinese University of Hong Kong, Shenzhen, with a visiting position at Westlake University, and was a recipient of the national scholarship.",
        image: "Figure/Committee/yujie.png",
      },
      {
        name: "Wentao Wang",
        role: "Member",
        initials: "WW",
        universities: ["University of Technology Sydney"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/wentao-wang-7847b536a/",
          github: "",
          email: "Wentao.Wang@student.uts.edu.au",
        },
        bio: "Wentao focuses on renewable energy forecasting, artificial intelligence, and data-driven modeling for energy systems. He received his PhD from the University of Technology Sydney, and was a recipient of the national scholarship for postgraduates and the UTS International Research Scholarship.",
        image: "Figure/Committee/wentao.png",
      },
      {
        name: "Zhongquan Chen",
        role: "Member",
        initials: "ZC",
        universities: ["Endhoven University of Technology"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/zhongquan-chen-78a708209/",
          github: "https://github.com/zhc079",
          email: "chenzhnq@gmail.com",
        },
        bio: "Zhongquan works on uncertainty quantification, multiscale model, and stochastic processes. The application includes network systems, energy transport in organic semiconductors.  His academic path includes a PhD in Applied Math from Eindhoven University of Technology, a Master degree from University of Saskatchewan, and a Bachelor from Sun Yat-sen University. At DeepPrior, Zhongquan Chen contributes to the research at the intersection of scientific ML, price prediction and optimization.",
        image: "Figure/Committee/zhongquan.png",
      },
      {
        name: "Jeffrey Xu",
        role: "Member",
        initials: "JX",
        universities: ["Hongkong University of Science and Technology"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/weifan-xu-jeffrey/",
          github: "",
          email: "wxubp@connect.ust.hk",
        },
        bio: "Jeffrey focuses on applying AI models to energy forecasting. His academic path includes a PhD from the Hong Kong University of Science and Technology, where he built Stellerus and Mission Rocket and worked on obtaining fundamental energy data. At DeepPrior, Jeffrey contributes to research at the intersection of AI, probabilistic forecasting, and electricity price prediction.",
        image: "Figure/Committee/jeffrey.png",
      },
      {
        name: "Shuyi Gao",
        role: "Member",
        initials: "SG",
        universities: ["Delft University of Technology"],
        links: {
          website: "",
          linkedin: "https://www.linkedin.com/in/shuyi-gao/",
          github: "",
          email: "s.gao@tudelft.nl",
        },
        bio: "Shuyi focuses on AI, battery dispatch, and electricity markets. Her research combines reinforcement learning, optimization, and agent-based modeling to improve decision-making in complex energy systems. Her academic path includes doctoral research at TU Delft in the Netherlands, where she develops AI-driven approaches for energy management, storage optimization, and power system operations, alongside work as a Quantitative Researcher in energy trading. At DeepPrior, Shuyi contributes to research at the intersection of AI, energy systems, and technological innovation.",
        image: "",
      },
    ],
  },
  research: {
    eyebrow: "Research",
    title: "A research archive built for depth.",
    description:
      "DeepPrior promotes reproducible and impactful research in energy markets and power systems.",
    papers: [
      {
        title: "PriceFM: Foundation Model for Probabilistic Electricity Price Forecasting",
        authors: "Runyao Yu, Chenhui Gu, Jochen Stiasny, Qingsong Wen, Wasim Sarwar Dilov, Lianlian Qi, Jochen L. Cremer",
        abstract: "A foundation-model approach for probabilistic day-ahead electricity price forecasting that leverages large-scale pretraining to generalize across bidding zones, horizons, and market conditions.",
        journal: "Preprint",
        year: "2026",
        paperUrl: "https://arxiv.org/abs/2508.04875",
        dataUrl: "https://huggingface.co/datasets/RunyaoYu/PriceFM/tree/main",
        codeUrl: "https://github.com/runyao-yu/PriceFM",
        bibtex: `@misc{yu2026pricefm,
  title={PriceFM: Foundation Model for Probabilistic Electricity Price Forecasting},
  author={Yu, Runyao and Gu, Chenhui and Stiasny, Jochen and Wen, Qingsong and Dilov, Wasim Sarwar and Qi, Lianlian and Cremer, Jochen L.},
  year={2026},
  eprint={2508.04875},
  archivePrefix={arXiv},
  url={https://arxiv.org/abs/2508.04875}
}`,
        figures: [
          {
            title: "Structure of PriceFM",
            image: "Figure/Research/Covers/pricefm.png",
          },
        ],
      },
      {
        title: "OrderFusion: Encoding Orderbook for End-to-End Probabilistic Intraday Electricity Price Forecasting",
        authors: "Runyao Yu, Yuchen Tao, Fabian Leimgruber, Tara Esterl, Jochen Stiasny, Derek W. Bunn, Qingsong Wen, Hongye Guo, Jochen L. Cremer",
        abstract: "An end-to-end probabilistic intraday electricity price forecasting framework that encodes orderbook structure directly to capture richer market-state information.",
        journal: "Preprint",
        year: "2026",
        paperUrl: "https://arxiv.org/pdf/2502.06830",
        dataUrl: "https://webshop.eex-group.com/epex-spot-public-market-data",
        codeUrl: "https://github.com/runyao-yu/OrderFusion",
        bibtex: `@misc{yu2026orderfusion,
  title={OrderFusion: Encoding Orderbook for End-to-End Probabilistic Intraday Electricity Price Forecasting},
  author={Yu, Runyao and Tao, Yuchen and Leimgruber, Fabian and Esterl, Tara and Stiasny, Jochen and Bunn, Derek W. and Wen, Qingsong and Guo, Hongye and Cremer, Jochen L.},
  year={2026},
  eprint={2502.06830},
  archivePrefix={arXiv},
  url={https://arxiv.org/abs/2502.06830}
}`,
        figures: [
          {
            title: "Structure of OrderFusion",
            image: "Figure/Research/Covers/orderfusion.png",
          },
        ],
      },
      {
        title: "Adapting to Drift: Weather-Pattern Experts for Short-Term Photovoltaic Power Forecasting",
        authors: "Wentao Wang, Haiyan Lu, Ayesha Ubaid, Fanyi Yang, Runyao Yu, Jianzhou Wang",
        abstract: "A weather-pattern expert approach for short-term photovoltaic forecasting under internal and external drift.",
        journal: "Advanced Engineering Informatics",
        year: "2026",
        paperUrl: "https://www.sciencedirect.com/science/article/pii/S1474034626004738",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{wang2026adapting,
  title={Adapting to Drift: Weather-Pattern Experts for Short-Term Photovoltaic Power Forecasting},
  author={Wang, Wentao and Lu, Haiyan and Ubaid, Ayesha and Yang, Fanyi and Yu, Runyao and Wang, Jianzhou},
  journal={Advanced Engineering Informatics},
  volume={74},
  pages={104781},
  year={2026},
  doi={10.1016/j.aei.2026.104781}
}`,
        figures: [
          {
            title: "Weather-pattern expert routing",
            image: "Figure/Research/Covers/adapting_to_drift.png",
          },
        ],
      },
      {
        title: "Volatility-Aware Sample Re-Weighting Framework for Short-Term Photovoltaic Power Forecasting",
        authors: "Wentao Wang, Haiyan Lu, Ayesha Ubaid, Fanyi Yang, Yan Zhao, Jianzhou Wang",
        abstract: "A sample re-weighting framework that adapts photovoltaic forecasting to volatility regimes.",
        journal: "Information Processing & Management",
        year: "2026",
        paperUrl: "https://www.sciencedirect.com/science/article/pii/S030645732600004X",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{wang2026volatility,
  title={Volatility-Aware Sample Re-Weighting Framework for Short-Term Photovoltaic Power Forecasting},
  author={Wang, Wentao and Lu, Haiyan and Ubaid, Ayesha and Yang, Fanyi and Zhao, Yan and Wang, Jianzhou},
  journal={Information Processing & Management},
  pages={104612},
  year={2026},
  doi={10.1016/j.ipm.2026.104612}
}`,
        figures: [
          {
            title: "Volatility-aware sample re-weighting",
            image: "Figure/Research/VolatilityReweighting.svg",
          },
        ],
      },
      {
        title: "Orderbook Feature Learning and Asymmetric Generalization in Intraday Electricity Markets",
        authors: "Runyao Yu, Ruochen Wu, Yongsheng Han, Jochen L. Cremer",
        abstract: "A benchmark of orderbook-derived features and model transfer across intraday electricity markets.",
        journal: "Power Systems Computation Conference",
        year: "2026",
        paperUrl: "https://arxiv.org/pdf/2510.12685",
        dataUrl: "https://webshop.eex-group.com/epex-spot-public-market-data",
        codeUrl: "https://runyao-yu.github.io/AsymGen/",
        bibtex: `@misc{yu2026orderbook,
  title={Orderbook Feature Learning and Asymmetric Generalization in Intraday Electricity Markets},
  author={Yu, Runyao and Wu, Ruochen and Han, Yongsheng and Cremer, Jochen L.},
  year={2026},
  eprint={2510.12685},
  archivePrefix={arXiv},
  url={https://arxiv.org/abs/2510.12685}
}`,
        figures: [
          {
            title: "Orderbook feature learning",
            image: "Figure/Research/Covers/orderbook_feature_learning_asymmetric.png",
          },
        ],
      },
      {
        title: "RobustSTL: A Robust Seasonal-Trend Decomposition Algorithm for Long Time Series",
        authors: "Qingsong Wen, Jingkun Gao, Xiaomin Song, Liang Sun, Huan Xu, Shenghuo Zhu",
        abstract: "A robust decomposition algorithm for long time series with complex seasonal and trend behavior.",
        journal: "AAAI Conference on Artificial Intelligence",
        year: "2019",
        paperUrl: "https://ojs.aaai.org/index.php/AAAI/article/view/4480",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@inproceedings{wen2019robuststl,
  title={RobustSTL: A Robust Seasonal-Trend Decomposition Algorithm for Long Time Series},
  author={Wen, Qingsong and Gao, Jingkun and Song, Xiaomin and Sun, Liang and Xu, Huan and Zhu, Shenghuo},
  booktitle={AAAI Conference on Artificial Intelligence},
  year={2019}
}`,
        figures: [
          {
            title: "Robust seasonal-trend decomposition",
            image: "Figure/Research/Covers/robuststl.png",
          },
        ],
      },
      {
        title: "Transformers in Time Series: A Survey",
        authors: "Qingsong Wen, Tian Zhou, Chaoli Zhang, Weiqi Chen, Ziqing Ma, Junchi Yan, Liang Sun",
        abstract: "A survey of transformer architectures, design choices, and applications for time-series modeling.",
        journal: "International Joint Conference on Artificial Intelligence",
        year: "2023",
        paperUrl: "https://arxiv.org/pdf/2202.07125",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{wen2023transformers,
  title={Transformers in Time Series: A Survey},
  author={Wen, Qingsong and Zhou, Tian and Zhang, Chaoli and Chen, Weiqi and Ma, Ziqing and Yan, Junchi and Sun, Liang},
  journal={International Joint Conference on Artificial Intelligence},
  year={2023}
}`,
        figures: [
          {
            title: "Transformers in time series",
            image: "Figure/Research/TransformersSurvey.png",
          },
        ],
      },
      {
        title: "Time Series Data Augmentation for Deep Learning: A Survey",
        authors: "Qingsong Wen, Liang Sun, Fan Yang, Xiaomin Song, Jingkun Gao, Xue Wang, Huan Xu",
        abstract: "A survey of augmentation methods for deep learning on time-series data.",
        journal: "International Joint Conference on Artificial Intelligence",
        year: "2021",
        paperUrl: "https://arxiv.org/pdf/2002.12478",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{wen2021timeseriesaugmentation,
  title={Time Series Data Augmentation for Deep Learning: A Survey},
  author={Wen, Qingsong and Sun, Liang and Yang, Fan and Song, Xiaomin and Gao, Jingkun and Wang, Xue and Xu, Huan},
  journal={International Joint Conference on Artificial Intelligence},
  year={2021}
}`,
        figures: [
          {
            title: "Time-series data augmentation",
            image: "Figure/Research/TimeSeriesAugmentation.png",
          },
        ],
      },
      {
        title: "A Cyber-Physical-Social Perspective on Future Smart Distribution Systems",
        authors: "Yi Wang, Chien-Fei Chen, Peng-Yong Kong, Husheng Li, Qingsong Wen",
        abstract: "A review of coupled cyber, physical, and social dimensions in future smart distribution systems.",
        journal: "Proceedings of the IEEE",
        year: "2023",
        paperUrl: "https://ieeexplore.ieee.org/document/9844442",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{wang2023cyberphysicalsocial,
  title={A Cyber-Physical-Social Perspective on Future Smart Distribution Systems},
  author={Wang, Yi and Chen, Chien-Fei and Kong, Peng-Yong and Li, Husheng and Wen, Qingsong},
  journal={Proceedings of the IEEE},
  year={2023},
  doi={10.1109/JPROC.2022.3192535}
}`,
        figures: [
          {
            title: "Cyber-physical-social distribution systems",
            image: "Figure/Research/Covers/cyber_physical.png",
          },
        ],
      },
      {
        title: "Learning Li-ion Battery Health and Degradation Modes from Data with Aging-Aware Circuit Models",
        authors: "Zihao Zhou, Antti Aitio, David Howey",
        abstract: "An aging-aware equivalent circuit model for estimating battery health and degradation modes from operational data.",
        journal: "Applied Energy",
        year: "2025",
        paperUrl: "https://www.sciencedirect.com/science/article/pii/S0306261925011055",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{zhou2025batteryhealth,
  title={Learning Li-ion Battery Health and Degradation Modes from Data with Aging-Aware Circuit Models},
  author={Zhou, Zihao and Aitio, Antti and Howey, David},
  journal={Applied Energy},
  volume={397},
  pages={126375},
  year={2025},
  doi={10.1016/j.apenergy.2025.126375}
}`,
        figures: [
          {
            title: "Aging-aware circuit model",
            image: "Figure/Research/Covers/degrade_aging_aware.png",
          },
        ],
      },
      {
        title: "Time-LLM: Time Series Forecasting by Reprogramming Large Language Models",
        authors: "Ming Jin, Shiyu Wang, Lintao Ma, Zhixuan Chu, James Y. Zhang, Xiaoming Shi, Pin-Yu Chen, Yuxuan Liang, Yuan-Fang Li, Shirui Pan, Qingsong Wen",
        abstract: "A reprogramming framework that adapts large language models to time-series forecasting.",
        journal: "International Conference on Learning Representations",
        year: "2024",
        paperUrl: "https://proceedings.iclr.cc/paper_files/paper/2024/file/680b2a8135b9c71278a09cafb605869e-Paper-Conference.pdf",
        dataUrl: "https://github.com/KimMeen/Time-LLM/tree/main/dataset",
        codeUrl: "https://github.com/KimMeen/Time-LLM",
        bibtex: `@inproceedings{jin2024timellm,
  title={Time-LLM: Time Series Forecasting by Reprogramming Large Language Models},
  author={Jin, Ming and Wang, Shiyu and Ma, Lintao and Chu, Zhixuan and Zhang, James Y. and Shi, Xiaoming and Chen, Pin-Yu and Liang, Yuxuan and Li, Yuan-Fang and Pan, Shirui and Wen, Qingsong},
  booktitle={International Conference on Learning Representations},
  year={2024}
}`,
        figures: [
          {
            title: "Time-LLM reprogramming",
            image: "Figure/Research/Covers/timellm.png",
          },
        ],
      },
      {
        title: "Foundation Models for Time Series Analysis: A Tutorial and Survey",
        authors: "Yuxuan Liang, Haomin Wen, Yuqi Nie, Yushan Jiang, Ming Jin, Dongjin Song, Shirui Pan, Qingsong Wen",
        abstract: "A tutorial and survey of foundation models for time-series analysis.",
        journal: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
        year: "2024",
        paperUrl: "https://dl.acm.org/doi/10.1145/3637528.3671451",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@inproceedings{liang2024foundation,
  title={Foundation Models for Time Series Analysis: A Tutorial and Survey},
  author={Liang, Yuxuan and Wen, Haomin and Nie, Yuqi and Jiang, Yushan and Jin, Ming and Song, Dongjin and Pan, Shirui and Wen, Qingsong},
  booktitle={Proceedings of the 30th ACM SIGKDD Conference on Knowledge Discovery and Data Mining},
  year={2024},
  doi={10.1145/3637528.3671451}
}`,
        figures: [
          {
            title: "Foundation models for time series",
            image: "Figure/Research/Covers/foundationmodel_survey.png",
          },
        ],
      },
      {
        title: "Simulating Cyber-Physical Energy Systems: Challenges, Tools and Methods",
        authors: "Peter Palensky, Edmund Widl, Atiyah Elsheikh",
        abstract: "A review of modeling challenges, tools, and simulation methods for cyber-physical energy systems.",
        journal: "IEEE Transactions on Systems, Man, and Cybernetics: Systems",
        year: "2014",
        paperUrl: "https://ieeexplore.ieee.org/document/6623196",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{palensky2014simulating,
  title={Simulating Cyber-Physical Energy Systems: Challenges, Tools and Methods},
  author={Palensky, Peter and Widl, Edmund and Elsheikh, Atiyah},
  journal={IEEE Transactions on Systems, Man, and Cybernetics: Systems},
  year={2014},
  doi={10.1109/TSMCC.2013.2265739}
}`,
        figures: [
          {
            title: "Cyber-physical energy simulation",
            image: "Figure/Research/SimulatingCyberPhysical.svg",
          },
        ],
      },
      {
        title: "Demand Side Management: Demand Response, Intelligent Energy Systems, and Smart Loads",
        authors: "Peter Palensky, Dietmar Dietrich",
        abstract: "A taxonomy and overview of demand-side management, demand response, and smart loads.",
        journal: "IEEE Transactions on Industrial Informatics",
        year: "2011",
        paperUrl: "https://ieeexplore.ieee.org/document/5930335",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{palensky2011demand,
  title={Demand Side Management: Demand Response, Intelligent Energy Systems, and Smart Loads},
  author={Palensky, Peter and Dietrich, Dietmar},
  journal={IEEE Transactions on Industrial Informatics},
  year={2011},
  doi={10.1109/TII.2011.2158841}
}`,
        figures: [
          {
            title: "Demand response and smart loads",
            image: "Figure/Research/DemandSideManagement.svg",
          },
        ],
      },
      {
        title: "Cosimulation of Intelligent Power Systems: Fundamentals, Software Architecture, Numerics, and Coupling",
        authors: "Peter Palensky, Arjen A. van der Meer, Claudio David Lopez, Arun Joseph, Kaikai Pan",
        abstract: "A review of co-simulation fundamentals, software architecture, numerics, and model coupling for intelligent power systems.",
        journal: "IEEE Industrial Electronics Magazine",
        year: "2017",
        paperUrl: "https://ieeexplore.ieee.org/document/7883974",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{palensky2017cosimulation,
  title={Cosimulation of Intelligent Power Systems: Fundamentals, Software Architecture, Numerics, and Coupling},
  author={Palensky, Peter and van der Meer, Arjen A. and Lopez, Claudio David and Joseph, Arun and Pan, Kaikai},
  journal={IEEE Industrial Electronics Magazine},
  year={2017},
  doi={10.1109/MIE.2016.2639825}
}`,
        figures: [
          {
            title: "Co-simulation architecture",
            image: "Figure/Research/Cosimulation.svg",
          },
        ],
      },
      {
        title: "Forecasting Loads and Prices in Competitive Power Markets",
        authors: "Derek W. Bunn",
        abstract: "A review of methodological issues and forecasting techniques for loads and prices in competitive power markets.",
        journal: "Proceedings of the IEEE",
        year: "2000",
        paperUrl: "https://ieeexplore.ieee.org/document/823996",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{bunn2000forecasting,
  title={Forecasting Loads and Prices in Competitive Power Markets},
  author={Bunn, Derek W.},
  journal={Proceedings of the IEEE},
  year={2000},
  doi={10.1109/5.823996}
}`,
        figures: [
          {
            title: "Power-market load and price forecasting",
            image: "Figure/Research/PowerMarkets.svg",
          },
        ],
      },
      {
        title: "Interaction of Judgemental and Statistical Forecasting Methods: Issues and Analysis",
        authors: "Derek W. Bunn, George Wright",
        abstract: "A study of how judgemental and statistical forecasting methods interact in forecasting practice.",
        journal: "Management Science",
        year: "1991",
        paperUrl: "https://pubsonline.informs.org/doi/abs/10.1287/mnsc.37.5.501",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{bunn1991interaction,
  title={Interaction of Judgemental and Statistical Forecasting Methods: Issues and Analysis},
  author={Bunn, Derek W. and Wright, George},
  journal={Management Science},
  year={1991},
  doi={10.1287/mnsc.37.5.501}
}`,
        figures: [
          {
            title: "Forecasting method interaction",
            image: "Figure/Research/JudgementalForecasting.svg",
          },
        ],
      },
      {
        title: "Experimental Study of a New Hybrid PSO with Mutation for Economic Dispatch with Non-Smooth Cost Function",
        authors: "Haiyan Lu, Pichet Sriyanyong, Yong Hua Song, Tharam Dillon",
        abstract: "A hybrid particle swarm optimization approach for economic dispatch problems with non-smooth cost functions.",
        journal: "International Journal of Electrical Power & Energy Systems",
        year: "2010",
        paperUrl: "https://www.sciencedirect.com/science/article/pii/S0142061510000669",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@article{lu2010hybridpso,
  title={Experimental Study of a New Hybrid PSO with Mutation for Economic Dispatch with Non-Smooth Cost Function},
  author={Lu, Haiyan and Sriyanyong, Pichet and Song, Yong Hua and Dillon, Tharam},
  journal={International Journal of Electrical Power & Energy Systems},
  volume={32},
  number={9},
  pages={921--935},
  year={2010},
  doi={10.1016/j.ijepes.2010.03.001}
}`,
        figures: [
          {
            title: "Hybrid PSO economic dispatch",
            image: "Figure/Research/EconomicDispatch.svg",
          },
        ],
      },
      {
        title: "Fast RobustSTL: Efficient and Robust Seasonal-Trend Decomposition for Time Series with Complex Patterns",
        authors: "Qingsong Wen, Zhe Zhang, Yan Li, Liang Sun",
        abstract: "An efficient and robust seasonal-trend decomposition method for complex time-series patterns.",
        journal: "ACM SIGKDD Conference on Knowledge Discovery and Data Mining",
        year: "2020",
        paperUrl: "https://dl.acm.org/doi/10.1145/3394486.3403271",
        dataUrl: "",
        codeUrl: "",
        bibtex: `@inproceedings{wen2020fastrobuststl,
  title={Fast RobustSTL: Efficient and Robust Seasonal-Trend Decomposition for Time Series with Complex Patterns},
  author={Wen, Qingsong and Zhang, Zhe and Li, Yan and Sun, Liang},
  booktitle={Proceedings of the 26th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining},
  year={2020},
  doi={10.1145/3394486.3403271}
}`,
        figures: [
          {
            title: "Fast robust seasonal-trend decomposition",
            image: "Figure/Research/FastRobustSTL.svg",
          },
        ],
      },
    ],
  },
  analysis: {
    eyebrow: "Insights",
    title: "Weekly insights built for signal.",
    description:
      "DeepPrior provides weekly energy insights to deliver timely and actionable signals.",
    posts: [
      {
        date: "11 Apr 2026",
        country: "Germany",
        feature: "Day-Ahead Prices",
        summary:
          "Weekend prices softened as wind generation strengthened into the evening peak and compressed upside risk.",
        details:
          "Use this card for a weekly note that isolates one market story, states the main signal in one sentence, and then explains the operational drivers, structural context, and likely implications in a short paragraph.",
        figures: [
          {
            title: "Price",
            image: "Figure/Analysis/2026_4_11/Price.jpg",
          },
          {
            title: "Solar",
            image: "Figure/Analysis/2026_4_11/Solar.jpg",
          },
          {
            title: "Wind",
            image: "Figure/Analysis/2026_4_11/Wind.jpg",
          },
        ],
      },

      {
        date: "04 Apr 2026",
        country: "Austria",
        feature: "Solar",
        summary:
          "Midday solar output capped intraday volatility, but the late ramp still widened balancing pressure into the close.",
        details:
          "Keep the top summary crisp and directional, then use this body copy for the fuller interpretation: what changed, why it mattered, and which feature or regime shift the figures below are meant to support.",
        figures: [],
      },

      {
        date: "03 Apr 2026",
        country: "Germany",
        feature: "Solar",
        summary:
          "Placeholder.",
        details:
          "Placeholder details.",
        figures: [],
      },

      {
        date: "01 Apr 2026",
        country: "Germany",
        feature: "Solar",
        summary:
          "Placeholder.",
        details:
          "Placeholder details.",
        figures: [],
      },





    ],
  },
  about: {
    eyebrow: "About DeepPrior",
    title: "A Research Organization with a Vision for Impact",
    visionTitle: "Our Vision",
    visionText:
      "At DeepPrior, our mission is to redefine the intelligence layer of European energy markets and power systems. We believe that the transition to a carbon-neutral future requires more than just raw data; it demands a deep understanding of the underlying operational and physical logic of energy systems. We are dedicated to exploring the intersection of deep learning and prior domain knowledge, transforming complex research into accurate forecasting engines.",
  },
  footer: {
    locationTitle: "Location",
    locationLines: ["Frankfurt am Main", "Germany"],
    contactTitle: "Contact",
    contactLines: ["deepprior@outlook.com", "+4917634640282"],
    socialTitle: "Social",
    socials: [
      {
        label: "LinkedIn",
        href: "https://www.linkedin.com/company/deepprior/",
      },
      {
        label: "X",
        href: "https://x.com/",
      },
    ],
  },
};
